#!/bin/bash

echo "Running unit tests..."

make fmt
status=$?
# return 1 exit code if running checks fails
[ $status -ne 0 ] && exit 1


make lint
status=$?
# return 1 exit code if running checks fails
[ $status -ne 0 ] && exit 1

exit 0

